version: '3.8'

services:
  relational-db:
    container_name: relational-db
    image: postgres:latest
    ports:
      - "$POSTGRES_PORT:5432"
    environment:
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_scripts/init_scripts:/docker-entrypoint-initdb.d
  
  kg-db:
    container_name: kg-db
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      NEO4J_AUTH: "$NEO4J_USER/$NEO4J_PASSWORD"
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-import:/var/lib/neo4j/import